/**
 * Hardcoded Data
 * ข้อมูล hardcode สำหรับแสดงผลในแอพพลิเคชั่น
 */

import { Gym, Event, Product, TrainingPackage, Article } from "@/types";

// Training Packages
export const PACKAGES: TrainingPackage[] = [
  {
    id: 1,
    name: "1 Day Pass",
    duration_days: 1,
    base_price: 500,
    description: "Single day training pass",
    inclusions: ["Training session", "Equipment use"],
  },
  {
    id: 2,
    name: "1 Week Pass",
    duration_days: 7,
    base_price: 3000,
    description: "One week training pass",
    inclusions: ["Training sessions", "Equipment use", "Towel service"],
  },
  {
    id: 3,
    name: "1 Month Pass",
    duration_days: 30,
    base_price: 10000,
    description: "One month unlimited training",
    inclusions: [
      "Unlimited training",
      "Equipment use",
      "Towel service",
      "Nutrition consultation",
    ],
  },
];

// Gyms
export const GYMS: Gym[] = [
  {
    id: "1",
    slug: "lumpinee-boxing-stadium",
    gym_name: "สนามมวยลุมพินี",
    gym_name_english: "Lumpinee Boxing Stadium",
    address: "6 Rama IV Road, Thung Maha Mek, Sathon, Bangkok 10120",
    gym_details:
      "One of the most prestigious Muay Thai stadiums in Thailand. Training facility with world-class trainers.",
    socials: "facebook.com/lumpinee",
    gym_type: "Professional",
    packages: PACKAGES,
  },
  {
    id: "2",
    slug: "fairtex-training-center",
    gym_name: "ค่ายมวยแฟร์เท็กซ์",
    gym_name_english: "Fairtex Training Center",
    address: "221/12 Moo 1, Bang Pla, Bang Phli, Samut Prakan 10540",
    gym_details:
      "World-renowned Muay Thai training camp. Fairtex has produced many champions.",
    socials: "facebook.com/fairtex",
    gym_type: "Professional",
    packages: PACKAGES,
  },
  {
    id: "3",
    slug: "tiger-muay-thai",
    gym_name: "ไทเกอร์ มวยไทย",
    gym_name_english: "Tiger Muay Thai",
    address: "7/11 Moo 5, Soi Ta-iad, Chalong, Phuket 83130",
    gym_details:
      "Located in Phuket, Tiger Muay Thai is one of the largest and most famous training camps in the world.",
    socials: "facebook.com/tigermuaythai",
    gym_type: "Professional",
    packages: PACKAGES,
  },
  {
    id: "4",
    slug: "petchyindee-academy",
    gym_name: "สถาบันเพชรยินดี",
    gym_name_english: "Petchyindee Academy",
    address: "123 Rama IV Road, Bangkok 10110",
    gym_details:
      "Historic gym with a legacy of producing top fighters. Traditional training methods combined with modern facilities.",
    socials: "facebook.com/petchyindee",
    gym_type: "Professional",
    packages: PACKAGES,
  },
];

// Events
export const EVENTS: Event[] = [
  {
    id: 1,
    slug: "one-championship-bangkok",
    name: "ONE Championship: Bangkok Fight Night",
    date: "2025-11-15T19:00:00.000Z",
    location: "Impact Arena, Bangkok",
    details:
      "Experience the best of Muay Thai and mixed martial arts at ONE Championship. World-class fighters compete for glory.",
    price: 1500,
    image: undefined,
  },
  {
    id: 2,
    slug: "lumpinee-friday-fights",
    name: "Lumpinee Stadium Friday Fights",
    date: "2025-10-25T18:00:00.000Z",
    location: "Lumpinee Boxing Stadium, Bangkok",
    details:
      "Traditional Muay Thai fights at the legendary Lumpinee Stadium. Every Friday night features top Thai fighters.",
    price: 800,
    image: undefined,
  },
  {
    id: 3,
    slug: "rajadamnern-championship",
    name: "Rajadamnern Stadium Championship",
    date: "2025-11-01T19:00:00.000Z",
    location: "Rajadamnern Stadium, Bangkok",
    details:
      "Championship fights at the historic Rajadamnern Stadium. Watch rising stars and established champions battle it out.",
    price: 1000,
    image: undefined,
  },
  {
    id: 4,
    slug: "thai-fight-phuket",
    name: "Thai Fight: Phuket Showdown",
    date: "2025-12-05T20:00:00.000Z",
    location: "Phuket Provincial Stadium",
    details:
      "Thai Fight brings exciting Muay Thai action to Phuket. International and Thai fighters compete in spectacular matches.",
    price: 1200,
    image: undefined,
  },
];

// Products
export const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: "fairtex-boxing-gloves-bgv1",
    nameThai: "นักชกถุงมือแฟร์เท็กซ์ BGV1",
    nameEnglish: "Fairtex Boxing Gloves BGV1",
    description:
      "Premium leather boxing gloves. Perfect for training and sparring.",
    price: 2500,
    stock: 50,
    category: "Equipment",
    image: undefined,
  },
  {
    id: 2,
    slug: "twins-special-shin-guards",
    nameThai: "สนับแข้ง Twins Special",
    nameEnglish: "Twins Special Shin Guards",
    description:
      "High-quality shin guards for Muay Thai training. Maximum protection.",
    price: 1800,
    stock: 30,
    category: "Equipment",
    image: undefined,
  },
  {
    id: 3,
    slug: "muay-thai-shorts-red",
    nameThai: "กางเกงมวยไทย สีแดง",
    nameEnglish: "Traditional Muay Thai Shorts - Red",
    description: "Authentic Thai-style fight shorts. Comfortable and durable.",
    price: 800,
    stock: 100,
    category: "Apparel",
    image: undefined,
  },
  {
    id: 4,
    slug: "hand-wraps-180-inch",
    nameThai: "ผ้าพันมือ 180 นิ้ว",
    nameEnglish: "Hand Wraps 180 inch",
    description: "Professional hand wraps. Essential for hand protection.",
    price: 200,
    stock: 200,
    category: "Equipment",
    image: undefined,
  },
  {
    id: 5,
    slug: "thai-oil-liniment",
    nameThai: "น้ำมันนวดไทย",
    nameEnglish: "Thai Boxing Liniment Oil",
    description: "Traditional Thai oil for warming up muscles before training.",
    price: 150,
    stock: 150,
    category: "Wellness",
    image: undefined,
  },
  {
    id: 6,
    slug: "heavy-bag-120cm",
    nameThai: "กระสอบทราย 120 ซม.",
    nameEnglish: "Heavy Bag 120cm",
    description: "Professional heavy bag for home or gym training.",
    price: 5500,
    stock: 15,
    category: "Equipment",
    image: undefined,
  },
];

// Articles
export const ARTICLES: Article[] = [
  {
    id: "1",
    slug: "muay-thai-history-traditions",
    title: "ประวัติและประเพณีมวยไทย: ศิลปะการต่อสู้ที่สืบทอดมาหลายศตวรรษ",
    excerpt: "มวยไทยเป็นมรดกทางวัฒนธรรมที่สำคัญของประเทศไทย เรียนรู้ประวัติศาสตร์และประเพณีอันยาวนานของศิลปะการต่อสู้นี้",
    content: "มวยไทยมีประวัติความเป็นมายาวนานหลายศตวรรษ เริ่มต้นจากการต่อสู้ป้องกันตัวของทหารไทยโบราณ...",
    author: "ครูมวย สมชาย",
    date: "2025-01-15",
    category: "ประวัติศาสตร์",
    tags: ["มวยไทย", "ประวัติศาสตร์", "วัฒนธรรม"],
  },
  {
    id: "2",
    slug: "basic-muay-thai-techniques",
    title: "เทคนิคพื้นฐานมวยไทยสำหรับผู้เริ่มต้น",
    excerpt: "คู่มือสำหรับผู้ที่สนใจเริ่มต้นฝึกมวยไทย พร้อมเทคนิคพื้นฐานที่ควรรู้",
    content: "การเริ่มต้นเรียนมวยไทยอาจดูยาก แต่ด้วยพื้นฐานที่ถูกต้อง คุณจะสามารถพัฒนาทักษะได้อย่างรวดเร็ว...",
    author: "ครูเทียน",
    date: "2025-01-10",
    category: "เทคนิค",
    tags: ["เทคนิค", "ผู้เริ่มต้น", "การฝึก"],
  },
  {
    id: "3",
    slug: "muay-thai-training-benefits",
    title: "5 ประโยชน์จากการฝึกมวยไทยที่คุณอาจไม่รู้",
    excerpt: "นอกจากการป้องกันตัว มวยไทยยังมีประโยชน์มากมายต่อสุขภาพและจิตใจ",
    content: "การฝึกมวยไทยไม่ได้ให้แค่ทักษะการต่อสู้เท่านั้น แต่ยังช่วยพัฒนาร่างกายและจิตใจอีกด้วย...",
    author: "นายแพทย์วิชัย",
    date: "2025-01-05",
    category: "สุขภาพ",
    tags: ["สุขภาพ", "ออกกำลังกาย", "ประโยชน์"],
  },
  {
    id: "4",
    slug: "famous-muay-thai-fighters",
    title: "นักมวยไทยในตำนาน 10 อันดับ",
    excerpt: "รู้จักกับนักมวยไทยที่ยิ่งใหญ่ที่สุดในประวัติศาสตร์",
    content: "มวยไทยมีนักมวยที่ยิ่งใหญ่มากมายที่สร้างประวัติศาสตร์ให้กับวงการ...",
    author: "นักข่าวกีฬา สุรชัย",
    date: "2024-12-28",
    category: "บุคคล",
    tags: ["นักมวย", "ตำนาน", "แชมป์เปี้ยน"],
  },
  {
    id: "5",
    slug: "muay-thai-equipment-guide",
    title: "คู่มือเลือกซื้ออุปกรณ์มวยไทยสำหรับผู้เริ่มต้น",
    excerpt: "ไกด์สำหรับการเลือกซื้อนวม สนับแข้ง และอุปกรณ์จำเป็นอื่นๆ",
    content: "การเลือกอุปกรณ์มวยไทยที่เหมาะสมสำคัญมากสำหรับผู้เริ่มต้น...",
    author: "ผู้เชี่ยวชาญอุปกรณ์ สมศักดิ์",
    date: "2024-12-20",
    category: "อุปกรณ์",
    tags: ["อุปกรณ์", "ผู้เริ่มต้น", "การซื้อ"],
  },
  {
    id: "6",
    slug: "muay-thai-diet-nutrition",
    title: "โภชนาการสำหรับนักมวยไทย: กินอย่างไรให้แข็งแรง",
    excerpt: "แนวทางการกินอาหารที่ถูกต้องสำหรับการฝึกมวยไทย",
    content: "โภชนาการที่ดีเป็นพื้นฐานสำคัญของการฝึกมวยไทยที่มีประสิทธิภาพ...",
    author: "นักโภชนาการ ดร.สุดา",
    date: "2024-12-15",
    category: "โภชนาการ",
    tags: ["อาหาร", "โภชนาการ", "สุขภาพ"],
  },
  {
    id: "7",
    slug: "new-fighter-program-2025",
    title: "เปิดตัวโปรแกรมนักสู้รุ่นใหม่ 2025 - โอกาสทองสำหรับเยาวชนไทย",
    excerpt: "โปรแกรมพัฒนานักสู้รุ่นใหม่เปิดรับสมัครแล้ว พร้อมทุนการศึกษาและโอกาสฝึกซ้อมกับโค้ชระดับโลก",
    content: "โปรแกรมนักสู้รุ่นใหม่ 2025 เปิดโอกาสให้เยาวชนไทยที่มีความฝันในการเป็นนักมวยไทยอาชีพ...",
    author: "คณะกรรมการพัฒนามวยไทย",
    date: "2025-01-20",
    category: "ข่าวสาร",
    tags: ["โปรแกรม", "เยาวชน", "ทุนการศึกษา"],
    isNew: true,
  },
  {
    id: "8",
    slug: "lumpinee-stadium-renovation",
    title: "สนามมวยลุมพินีเปิดใช้หลังการปรับปรุง - พร้อมต้อนรับแฟนมวย",
    excerpt: "สนามมวยลุมพินีเปิดให้บริการอีกครั้งหลังการปรับปรุงครั้งใหญ่ พร้อมระบบเทคโนโลยีทันสมัย",
    content: "สนามมวยลุมพินีที่ได้รับการปรับปรุงครั้งใหญ่ได้เปิดให้บริการอีกครั้งแล้ว...",
    author: "ผู้จัดการสนามลุมพินี",
    date: "2025-01-18",
    category: "ข่าวสาร",
    tags: ["ลุมพินี", "สนามมวย", "การปรับปรุง"],
  },
  {
    id: "9",
    slug: "muay-thai-world-championship-2025",
    title: "การแข่งขันมวยไทยชิงแชมป์โลก 2025 - นักสู้ไทยเตรียมความพร้อม",
    excerpt: "การแข่งขันมวยไทยชิงแชมป์โลกปี 2025 จะจัดขึ้นในประเทศไทย นักสู้ไทยเตรียมความพร้อมอย่างเต็มที่",
    content: "การแข่งขันมวยไทยชิงแชมป์โลก 2025 เป็นการแข่งขันที่ยิ่งใหญ่ที่สุดของปี...",
    author: "สมาคมมวยไทยแห่งประเทศไทย",
    date: "2025-01-16",
    category: "ข่าวสาร",
    tags: ["ชิงแชมป์โลก", "การแข่งขัน", "นักสู้ไทย"],
  },
  {
    id: "10",
    slug: "muay-thai-olympic-recognition",
    title: "มวยไทยได้รับการยอมรับเป็นกีฬาโอลิมปิก - ความภาคภูมิใจของคนไทย",
    excerpt: "มวยไทยได้รับการยอมรับอย่างเป็นทางการให้เป็นกีฬาโอลิมปิก นับเป็นความภาคภูมิใจของคนไทยทั้งชาติ",
    content: "การที่มวยไทยได้รับการยอมรับให้เป็นกีฬาโอลิมปิกถือเป็นความสำเร็จที่ยิ่งใหญ่...",
    author: "คณะกรรมการโอลิมปิกแห่งประเทศไทย",
    date: "2025-01-14",
    category: "ข่าวสาร",
    tags: ["โอลิมปิก", "การยอมรับ", "ความภาคภูมิใจ"],
    isNew: true,
  },
  {
    id: "11",
    slug: "muay-thai-training-camp-phuket",
    title: "ค่ายฝึกซ้อมมวยไทยที่ภูเก็ต - ดึงดูดนักท่องเที่ยวจากทั่วโลก",
    excerpt: "ค่ายฝึกซ้อมมวยไทยในภูเก็ตกลายเป็นจุดหมายปลายทางยอดนิยมสำหรับนักท่องเที่ยวที่สนใจศิลปะการต่อสู้",
    content: "ภูเก็ตได้กลายเป็นศูนย์กลางการฝึกซ้อมมวยไทยที่สำคัญของโลก...",
    author: "การท่องเที่ยวแห่งประเทศไทย",
    date: "2025-01-12",
    category: "ข่าวสาร",
    tags: ["ภูเก็ต", "ค่ายฝึก", "การท่องเที่ยว"],
  },
  {
    id: "12",
    slug: "muay-thai-education-curriculum",
    title: "มวยไทยเข้าสู่หลักสูตรการศึกษา - ส่งเสริมวัฒนธรรมไทยในโรงเรียน",
    excerpt: "กระทรวงศึกษาธิการประกาศบรรจุมวยไทยเป็นวิชาเลือกในหลักสูตรการศึกษาขั้นพื้นฐาน",
    content: "การบรรจุมวยไทยเป็นวิชาเลือกในหลักสูตรการศึกษาจะช่วยส่งเสริมวัฒนธรรมไทย...",
    author: "กระทรวงศึกษาธิการ",
    date: "2025-01-10",
    category: "ข่าวสาร",
    tags: ["การศึกษา", "หลักสูตร", "วัฒนธรรม"],
  },
];

