-- ============================================================================
-- SEED DATA FOR TESTING
-- ============================================================================
-- NOTE: Test users are created via scripts/create-test-users.sh
-- All test users have the password: "password123"
-- Run: ./scripts/create-test-users.sh after running migrations
-- ============================================================================

-- NOTE: auth.users are now created via Admin API script (see scripts/create-test-users.sh)
-- This ensures passwords are hashed correctly by Supabase Auth

-- ============================================================================
-- SEED DATA SUMMARY
-- ============================================================================
-- To create test users, run: ./scripts/create-test-users.sh
--
-- Test Users:
--   Admin: admin@muaythai.com / password123
--   Regular User: user@muaythai.com / password123
--   Partner 1: partner1@muaythai.com / password123
--   Partner 2: partner2@muaythai.com / password123
--
-- After creating users via the script, you can:
--   1. Set admin role manually in database
--   2. Create gym applications for partners
-- ============================================================================
