/**
 * Gyms API Endpoint (Admin Only)
 * 
 * GET /api/gyms - List all gyms
 * POST /api/gyms - Create new gym
 */

import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { withAdminAuth } from '@/lib/api/withAdminAuth';

const getGymsHandler = withAdminAuth(async (
    _request, 
    _context, 
    _user
) => {
  try {
    const supabase = await createClient();

    // Fetch all gyms
    const { data: gyms, error } = await supabase
      .from('gyms')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching gyms:', error);
      return NextResponse.json(
        { error: 'Failed to fetch gyms' },
        { status: 500 }
      );
    }

    // Fetch profiles for all gym owners
    const userIds = [...new Set(gyms?.map(g => g.user_id) || [])];
    const { data: profiles } = await supabase
      .from('profiles')
      .select('user_id, username, full_name')
      .in('user_id', userIds);

    // Merge profiles with gyms
    const gymsWithProfiles = gyms?.map(gym => ({
      ...gym,
      profiles: profiles?.find(p => p.user_id === gym.user_id) || null
    })) || [];

    return NextResponse.json({
      success: true,
      count: gymsWithProfiles.length,
      gyms: gymsWithProfiles,
    });

  } catch (error) {
    console.error('API Error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
});

export { getGymsHandler as GET };

/**
 * POST /api/gyms
 * สร้างยิมใหม่ (Admin only)
 */
const postGymHandler = withAdminAuth(async (
    request, 
    _context, 
    user
) => {
  try {
    const supabase = await createClient();

    // อ่าน request body
    const body = await request.json();
    const {
      gym_name,
      gym_name_english,
      contact_name,
      phone,
      email,
      website,
      location,
      gym_details,
      services,
      status,
    } = body;

    // Validation
    const errors: Record<string, string> = {};

    if (!gym_name || gym_name.trim().length < 3 || gym_name.trim().length > 100) {
      errors.gym_name = 'ชื่อยิมต้องมีความยาว 3-100 ตัวอักษร';
    }

    if (gym_name_english && (gym_name_english.trim().length < 3 || gym_name_english.trim().length > 100)) {
      errors.gym_name_english = 'ชื่อภาษาอังกฤษต้องมีความยาว 3-100 ตัวอักษร';
    }

    if (!contact_name || contact_name.trim().length < 2 || contact_name.trim().length > 100) {
      errors.contact_name = 'ชื่อผู้ติดต่อต้องมีความยาว 2-100 ตัวอักษร';
    }

    if (!phone) {
      errors.phone = 'กรุณากรอกเบอร์โทรศัพท์';
    } else {
      const phoneRegex = /^0\d{1,2}-?\d{3,4}-?\d{4}$/;
      if (!phoneRegex.test(phone.replace(/\s/g, ''))) {
        errors.phone = 'รูปแบบเบอร์โทรศัพท์ไม่ถูกต้อง (ตัวอย่าง: 02-123-4567 หรือ 0812345678)';
      }
    }

    if (!email) {
      errors.email = 'กรุณากรอกอีเมล';
    } else {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        errors.email = 'รูปแบบอีเมลไม่ถูกต้อง';
      }
    }

    if (website) {
      try {
        new URL(website);
      } catch {
        errors.website = 'รูปแบบ URL ไม่ถูกต้อง';
      }
    }

    if (!location || location.trim().length < 10) {
      errors.location = 'ที่อยู่ต้องมีความยาวอย่างน้อย 10 ตัวอักษร';
    }

    if (status && !['pending', 'approved', 'rejected'].includes(status)) {
      errors.status = 'สถานะไม่ถูกต้อง';
    }

    // ถ้ามี validation errors
    if (Object.keys(errors).length > 0) {
      return NextResponse.json(
        {
          success: false,
          error: 'ข้อมูลไม่ถูกต้อง',
          errors,
        },
        { status: 400 }
      );
    }

    // สร้างยิมใหม่
    const newGym = {
      user_id: user.id,
      gym_name: gym_name.trim(),
      gym_name_english: gym_name_english?.trim() || null,
      contact_name: contact_name.trim(),
      phone: phone.trim(),
      email: email.trim(),
      website: website?.trim() || null,
      location: location.trim(),
      gym_details: gym_details?.trim() || null,
      services: services || [],
      images: [],
      status: status || 'approved', // Default เป็น approved เพราะ admin สร้างเอง
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      // Note: slug will be auto-generated by database trigger from gym_name_english
    };

    const { data: createdGym, error: createError } = await supabase
      .from('gyms')
      .insert([newGym])
      .select()
      .single();

    if (createError) {
      throw createError;
    }

    return NextResponse.json({
      success: true,
      message: 'สร้างยิมใหม่สำเร็จ',
      data: createdGym,
    });

  } catch (error) {
    console.error('Error creating gym:', error);
    return NextResponse.json(
      {
        success: false,
        error: 'เกิดข้อผิดพลาดในการสร้างยิม',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
});

export { postGymHandler as POST };

