'use client';

import Link from 'next/link';
import { useTodos } from '@/hooks/useTodos';
import { TodoForm } from '@/components/todos/TodoForm';
import { TodoList } from '@/components/todos/TodoList';
import { Loading } from '@/components/ui/Loading';
import { ErrorMessage } from '@/components/ui/ErrorMessage';

export default function TodosPage() {
  const { todos, loading, error, addTodo, toggleTodo, deleteTodo } = useTodos();

  const handleAddTodo = async (task: string) => {
    const result = await addTodo(task);
    if (!result.success) {
      alert('เกิดข้อผิดพลาด: ' + result.error);
    }
  };

  const handleToggleTodo = async (id: number, isComplete: boolean) => {
    const result = await toggleTodo(id, isComplete);
    if (!result.success) {
      alert('เกิดข้อผิดพลาด: ' + result.error);
    }
  };

  const handleDeleteTodo = async (id: number) => {
    const result = await deleteTodo(id);
    if (!result.success) {
      alert('เกิดข้อผิดพลาด: ' + result.error);
    }
  };

  return (
    <div className="bg-gradient-to-b from-gray-50 dark:from-gray-900 to-gray-100 dark:to-gray-800 py-12 min-h-screen">
      <div className="mx-auto px-4 max-w-3xl container">
        <Link 
          href="/"
          className="inline-flex items-center mb-6 text-blue-600 hover:text-blue-700"
        >
          ← กลับหน้าแรก
        </Link>

        <div className="bg-white dark:bg-gray-800 shadow-lg p-8 rounded-xl">
          <h1 className="mb-6 font-bold text-gray-800 dark:text-white text-3xl">
            📝 Todo App
          </h1>

          {error && (
            <ErrorMessage 
              message={error}
              details={
                <details className="mt-2">
                  <summary className="text-yellow-700 dark:text-yellow-300 text-sm cursor-pointer">
                    คลิกเพื่อดูวิธีสร้างตาราง
                  </summary>
                  <pre className="bg-gray-900 mt-2 p-3 rounded overflow-x-auto text-green-400 text-xs">
{`-- SQL สำหรับสร้างตาราง todos
create table todos (
  id bigint generated by default as identity primary key,
  task text not null,
  is_complete boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table todos enable row level security;

-- Allow anyone to read todos
create policy "Anyone can read todos"
  on todos for select
  to public
  using (true);

-- Allow anyone to insert todos
create policy "Anyone can insert todos"
  on todos for insert
  to public
  with check (true);

-- Allow anyone to update todos
create policy "Anyone can update todos"
  on todos for update
  to public
  using (true);

-- Allow anyone to delete todos
create policy "Anyone can delete todos"
  on todos for delete
  to public
  using (true);`}
                  </pre>
                </details>
              }
            />
          )}

          <TodoForm onSubmit={handleAddTodo} />

          {loading ? (
            <Loading />
          ) : (
            <TodoList 
              todos={todos}
              onToggle={handleToggleTodo}
              onDelete={handleDeleteTodo}
            />
          )}

          <div className="mt-6 pt-6 border-gray-200 dark:border-gray-700 border-t">
            <p className="text-gray-600 dark:text-gray-400 text-sm">
              รายการทั้งหมด: {todos.length} | เสร็จแล้ว: {todos.filter(t => t.is_complete).length}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

