-- ============================================
-- Supabase Database Setup Script
-- ============================================
-- ไฟล์นี้มี SQL สำหรับสร้างตารางและ policies ต่างๆ
-- รันใน Supabase SQL Editor: https://app.supabase.com
-- ============================================

-- ============================================
-- 1. Todo Table
-- ============================================
-- สำหรับ Todo App Example

-- สร้างตาราง todos
CREATE TABLE IF NOT EXISTS todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task TEXT NOT NULL,
  is_complete BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- เปิดใช้งาน Row Level Security
ALTER TABLE todos ENABLE ROW LEVEL SECURITY;

-- Policy: ให้ทุกคนอ่านได้
CREATE POLICY "Anyone can read todos"
  ON todos FOR SELECT
  TO public
  USING (true);

-- Policy: ให้ทุกคนเพิ่มได้
CREATE POLICY "Anyone can insert todos"
  ON todos FOR INSERT
  TO public
  WITH CHECK (true);

-- Policy: ให้ทุกคนแก้ไขได้
CREATE POLICY "Anyone can update todos"
  ON todos FOR UPDATE
  TO public
  USING (true);

-- Policy: ให้ทุกคนลบได้
CREATE POLICY "Anyone can delete todos"
  ON todos FOR DELETE
  TO public
  USING (true);

-- ============================================
-- 2. User Profiles Table (Optional)
-- ============================================
-- สำหรับเก็บข้อมูลเพิ่มเติมของผู้ใช้

CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- เปิดใช้งาน Row Level Security
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Policy: ให้ทุกคนอ่าน profile ได้
CREATE POLICY "Public profiles are viewable by everyone"
  ON profiles FOR SELECT
  TO public
  USING (true);

-- Policy: ให้เจ้าของ profile แก้ไขของตัวเองได้
CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id);

-- Policy: ให้เจ้าของ profile เพิ่มข้อมูลของตัวเองได้
CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

-- ============================================
-- 3. Function: Auto-create profile on signup
-- ============================================
-- สร้าง profile อัตโนมัติเมื่อมีการสมัครใช้งาน

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger: เรียก function เมื่อมีผู้ใช้ใหม่
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================
-- 4. Example: Posts Table (สำหรับ Blog หรือ Social App)
-- ============================================
-- ตัวอย่างตารางที่ผูกกับผู้ใช้

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  content TEXT,
  published BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- เปิดใช้งาน Row Level Security
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Policy: ให้ทุกคนอ่านโพสต์ที่ publish แล้ว
CREATE POLICY "Public posts are viewable by everyone"
  ON posts FOR SELECT
  TO public
  USING (published = true);

-- Policy: ให้เจ้าของเห็นโพสต์ของตัวเองทั้งหมด
CREATE POLICY "Users can view own posts"
  ON posts FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Policy: ให้เจ้าของสร้างโพสต์ได้
CREATE POLICY "Users can create own posts"
  ON posts FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Policy: ให้เจ้าของแก้ไขโพสต์ของตัวเองได้
CREATE POLICY "Users can update own posts"
  ON posts FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id);

-- Policy: ให้เจ้าของลบโพสต์ของตัวเองได้
CREATE POLICY "Users can delete own posts"
  ON posts FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- ============================================
-- 5. Updated_at Trigger Function
-- ============================================
-- ฟังก์ชันสำหรับอัปเดต updated_at อัตโนมัติ

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- เพิ่ม trigger สำหรับตารางที่ต้องการ
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_posts_updated_at ON posts;
CREATE TRIGGER update_posts_updated_at
  BEFORE UPDATE ON posts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- เสร็จสิ้น!
-- ============================================
-- คุณสามารถคัดลอกส่วนที่ต้องการไปรันใน Supabase SQL Editor
-- หรือรันทั้งไฟล์เลยก็ได้