import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/database/supabase/server';

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();

    // Check if user is authenticated
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const {
      orderId,
      gymId,
      startDate,
      endDate,
      durationDays,
      packageType,
      packageName,
      packageNameEn,
      unitPrice,
      totalPrice,
      notes,
      specialRequests,
    } = body;

    // Validate required fields
    if (
      !orderId ||
      !gymId ||
      !startDate ||
      !endDate ||
      !durationDays ||
      !packageType ||
      !packageName ||
      !unitPrice ||
      !totalPrice
    ) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Create gym booking (using unified bookings table)
    const { data: booking, error: bookingError } = await supabase
      .from('bookings')
      .insert({
        order_id: orderId,
        user_id: user.id,
        gym_id: gymId,
        booking_number: '', // Will be auto-generated by trigger
        customer_name: user.user_metadata?.full_name || 'Unknown',
        customer_email: user.email || '',
        customer_phone: user.user_metadata?.phone || '',
        start_date: startDate,
        end_date: endDate,
        price_paid: totalPrice,
        package_name: packageName,
        package_type: packageType,
        duration_months: Math.ceil(durationDays / 30), // Convert days to months
        special_requests: specialRequests || notes,
        payment_status: 'pending',
        status: 'pending',
      })
      .select()
      .single();

    if (bookingError) {
      console.error('Error creating gym booking:', bookingError);
      return NextResponse.json(
        { error: 'Failed to create gym booking' },
        { status: 500 }
      );
    }

    return NextResponse.json(booking);
  } catch (error) {
    console.error('Error in gym booking API:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();

    // Check if user is authenticated
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get user's gym bookings using helper function (recommended)
    const { data: bookings, error: bookingsError } = await supabase.rpc(
      'get_user_bookings',
      { user_id_param: user.id }
    );

    // Alternative: Direct query from bookings table
    // const { data: bookings, error: bookingsError } = await supabase
    //   .from('bookings')
    //   .select(
    //     `
    //     *,
    //     gyms (
    //       id,
    //       gym_name,
    //       gym_name_english,
    //       location,
    //       slug,
    //       images
    //     ),
    //     orders (
    //       id,
    //       order_number,
    //       status,
    //       total_amount
    //     )
    //   `
    //   )
    //   .eq('user_id', user.id)
    //   .order('created_at', { ascending: false });

    if (bookingsError) {
      console.error('Error fetching gym bookings:', bookingsError);
      return NextResponse.json(
        { error: 'Failed to fetch gym bookings' },
        { status: 500 }
      );
    }

    return NextResponse.json(bookings);
  } catch (error) {
    console.error('Error in gym bookings API:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
