import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/database/supabase/server';
import { awardPoints, updateUserStreak } from '@/services/gamification.service';
import { sendBookingConfirmationEmail } from '@/lib/email';

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();

    // Check if user is authenticated
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const {
      orderId,
      gymId,
      startDate,
      endDate,
      durationDays,
      packageType,
      packageName,
      unitPrice,
      totalPrice,
      notes,
      specialRequests,
    } = body;

    // Validate required fields
    if (
      !orderId ||
      !gymId ||
      !startDate ||
      !endDate ||
      !durationDays ||
      !packageType ||
      !packageName ||
      !unitPrice ||
      !totalPrice
    ) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Create gym booking (using unified bookings table)
    const { data: booking, error: bookingError } = await supabase
      .from('bookings')
      .insert({
        order_id: orderId,
        user_id: user.id,
        gym_id: gymId,
        booking_number: '', // Will be auto-generated by trigger
        customer_name: user.user_metadata?.full_name || 'Unknown',
        customer_email: user.email || '',
        customer_phone: user.user_metadata?.phone || '',
        start_date: startDate,
        end_date: endDate,
        price_paid: totalPrice,
        package_name: packageName,
        package_type: packageType,
        duration_months: Math.ceil(durationDays / 30), // Convert days to months
        special_requests: specialRequests || notes,
        payment_status: 'pending',
        status: 'pending',
      })
      .select()
      .single();

    if (bookingError) {
      console.error('Error creating gym booking:', bookingError);
      return NextResponse.json(
        { error: 'Failed to create gym booking' },
        { status: 500 }
      );
    }

    // Send booking confirmation email
    try {
      // Fetch gym details for email
      const { data: gym } = await supabase
        .from('gyms')
        .select('gym_name, gym_name_english, slug')
        .eq('id', gymId)
        .single();

      if (gym && booking) {
        await sendBookingConfirmationEmail({
          to: booking.customer_email || user.email || '',
          customerName: booking.customer_name || 'คุณลูกค้า',
          bookingNumber: booking.booking_number || '',
          gymName: gym.gym_name || gym.gym_name_english || 'ค่ายมวย',
          packageName: booking.package_name || packageName,
          packageType: (booking.package_type as 'one_time' | 'package') || packageType as 'one_time' | 'package',
          startDate: booking.start_date,
          endDate: booking.end_date,
          pricePaid: booking.price_paid || totalPrice,
          customerPhone: booking.customer_phone,
          specialRequests: booking.special_requests || specialRequests,
          bookingUrl: gym.slug ? `/dashboard/bookings` : undefined,
        });

        // Create in-app notification
        await supabase
          .from('notifications')
          .insert({
            user_id: user.id,
            type: 'booking_confirmation',
            title: 'ยืนยันการจองสำเร็จ',
            message: `การจองของคุณ ${booking.booking_number || 'ใหม่'} ได้รับการยืนยันแล้ว`,
            link_url: '/dashboard/bookings',
            metadata: {
              booking_id: booking.id,
              booking_number: booking.booking_number,
            },
          });
      }
    } catch (emailError) {
      // Don't fail the booking if email fails
      console.warn('Email notification error (booking still successful):', emailError);
    }

    // Award gamification points for booking
    try {
      // Check if this is user's first booking
      const { data: existingBookings } = await supabase
        .from('bookings')
        .select('id')
        .eq('user_id', user.id)
        .limit(1);

      const isFirstBooking = !existingBookings || existingBookings.length === 0;

      // Award points based on booking type and duration
      let pointsToAward = isFirstBooking ? 100 : 50;
      
      // Bonus points for long-term packages
      if (packageType === 'package' && durationDays >= 180) {
        pointsToAward += 75; // Long-term package bonus
      }

      await awardPoints({
        user_id: user.id,
        points: pointsToAward,
        action_type: 'booking',
        action_description: isFirstBooking ? 'จองค่ายมวยครั้งแรก' : 
                           packageType === 'package' ? 'จองแพ็คเกจระยะยาว' : 'จองค่ายมวย',
        reference_id: booking.id,
        reference_type: 'booking',
      });

      // Update booking streak
      await updateUserStreak({
        user_id: user.id,
        streak_type: 'booking',
      });

    } catch (gamificationError) {
      // Don't fail the booking if gamification fails
      console.warn('Gamification error (booking still successful):', gamificationError);
    }

    return NextResponse.json(booking);
  } catch (error) {
    console.error('Error in gym booking API:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  try {
    const supabase = await createClient();

    // Check if user is authenticated
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get user's gym bookings using helper function (recommended)
    const { data: bookings, error: bookingsError } = await supabase.rpc(
      'get_user_bookings',
      { user_id_param: user.id }
    );

    // Alternative: Direct query from bookings table
    // const { data: bookings, error: bookingsError } = await supabase
    //   .from('bookings')
    //   .select(
    //     `
    //     *,
    //     gyms (
    //       id,
    //       gym_name,
    //       gym_name_english,
    //       location,
    //       slug,
    //       images
    //     ),
    //     orders (
    //       id,
    //       order_number,
    //       status,
    //       total_amount
    //     )
    //   `
    //   )
    //   .eq('user_id', user.id)
    //   .order('created_at', { ascending: false });

    if (bookingsError) {
      console.error('Error fetching gym bookings:', bookingsError);
      return NextResponse.json(
        { error: 'Failed to fetch gym bookings' },
        { status: 500 }
      );
    }

    return NextResponse.json(bookings);
  } catch (error) {
    console.error('Error in gym bookings API:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
